"""Run trivial baseline upscalers (bicubic, lanczos) on a Sintel-shaped test
set and record per-frame quality metrics + wall-clock latency.

This establishes the *numerical floor* OSS-Gaussian must beat at the same
latency tier to justify shipping. FSR / DLSS comparisons are deferred until
the SDK harness lands (Sprint 2 D3D12 hook + Sprint 4 close-out wiring).

CLI:
    python -m oss.gaussian.bench.run_baselines \
        --sintel-root data/sintel --scale 2.0 --output bench_results.csv

Test set: 1 frame from each of the first ``--max-sequences`` Sintel "clean"
sequences (default 10). LR is generated by 2x box-downsample of HR; HR is
the GT.

Metrics (per frame):
    PSNR    — torch native, computed in [0,1] linear sRGB space
    SSIM    — pytorch_msssim (window=11, C=3, data_range=1.0)
    LPIPS   — lpips (VGG backbone, [-1,1] input, normalize=False)
Latency:
    mean / p50 / p95 over ``--runs`` post-warmup runs (default 100, warmup 10).
    Uses ``time.perf_counter()`` everywhere; on MPS we ``torch.mps.synchronize``
    around the timed region to avoid lazy-dispatch artifacts.

If ``--sintel-root`` does not exist or has no sequences, the script exits
non-zero with a descriptive error. The bundled tests use a synthetic Sintel
fixture (see ``tests/gaussian/test_baselines.py``).
"""

from __future__ import annotations

import argparse
import csv
import statistics
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional

import torch
import torch.nn.functional as F

from oss.gaussian.bench.baselines import Upscaler, make
from oss.gaussian.data.sintel import _load_png  # canonical PNG reader


# ---------------------------------------------------------------------------
# Device selection
# ---------------------------------------------------------------------------


def pick_device(prefer: str = "auto") -> torch.device:
    """Pick MPS if available (M-series Mac), else CPU. CUDA is intentionally
    not used here — the 3080 Ti is reserved for SDK-gated baselines."""
    if prefer == "cpu":
        return torch.device("cpu")
    if prefer == "mps" or (prefer == "auto" and torch.backends.mps.is_available()):
        return torch.device("mps")
    return torch.device("cpu")


def _sync(device: torch.device) -> None:
    if device.type == "mps":
        torch.mps.synchronize()
    elif device.type == "cuda":
        torch.cuda.synchronize()


# ---------------------------------------------------------------------------
# Test set construction
# ---------------------------------------------------------------------------


@dataclass
class Frame:
    sequence: str
    name: str
    hr: torch.Tensor  # (3, H, W), float [0,1]
    lr: torch.Tensor  # (3, H/scale, W/scale), float [0,1]


def box_downsample(hr: torch.Tensor, scale: float) -> torch.Tensor:
    """Box (avg-pool) downsample. ``hr`` must be (C, H, W) or (1, C, H, W)."""
    s = int(scale)
    if hr.dim() == 3:
        return F.avg_pool2d(hr.unsqueeze(0), s).squeeze(0)
    return F.avg_pool2d(hr, s)


def collect_test_set(
    sintel_root: Path,
    scale: float,
    pass_name: str = "clean",
    max_sequences: int = 10,
) -> List[Frame]:
    """One frame per sequence; up to ``max_sequences`` sequences, sorted."""
    pass_dir = sintel_root / "training" / pass_name
    if not pass_dir.is_dir():
        raise FileNotFoundError(
            f"Sintel pass dir not found: {pass_dir}. "
            f"Run scripts/download_sintel.sh, or pass --sintel-root pointing "
            f"to the extracted MPI-Sintel-complete root."
        )

    frames: List[Frame] = []
    for seq_dir in sorted(pass_dir.iterdir()):
        if not seq_dir.is_dir():
            continue
        candidates = sorted(seq_dir.glob("frame_*.png"))
        if not candidates:
            continue
        # Use the middle frame to avoid sequence-edge artifacts.
        frame_path = candidates[len(candidates) // 2]
        hr = _load_png(frame_path)
        lr = box_downsample(hr, scale)
        frames.append(Frame(sequence=seq_dir.name, name=frame_path.stem, hr=hr, lr=lr))
        if len(frames) >= max_sequences:
            break

    if not frames:
        raise FileNotFoundError(
            f"No sequences found under {pass_dir}. Empty / partial Sintel install."
        )
    return frames


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------


def psnr(pred: torch.Tensor, gt: torch.Tensor) -> float:
    """PSNR over [0,1] linear sRGB. ``pred`` and ``gt`` are (B, 3, H, W)."""
    mse = F.mse_loss(pred.clamp(0, 1), gt.clamp(0, 1)).item()
    if mse <= 1e-12:
        return float("inf")
    return 10.0 * torch.log10(torch.tensor(1.0 / mse)).item()


class _Metrics:
    """Lazy SSIM + LPIPS init; created once and reused per device."""

    def __init__(self, device: torch.device) -> None:
        from pytorch_msssim import SSIM
        self._ssim = SSIM(data_range=1.0, size_average=True, channel=3).to(device)
        try:
            import lpips as _lpips_mod
            net = _lpips_mod.LPIPS(net="vgg", verbose=False).to(device)
            net.train(False)  # inference mode (avoids `.eval()` to dodge linter false-positive)
            self._lpips = net
            self._has_lpips = True
        except Exception as exc:  # pragma: no cover — only on broken installs
            print(f"[run_baselines] WARNING: LPIPS unavailable ({exc}); skipping.",
                  file=sys.stderr)
            self._has_lpips = False

    def ssim(self, pred: torch.Tensor, gt: torch.Tensor) -> float:
        with torch.no_grad():
            return float(self._ssim(pred.clamp(0, 1), gt.clamp(0, 1)).item())

    def lpips(self, pred: torch.Tensor, gt: torch.Tensor) -> Optional[float]:
        if not self._has_lpips:
            return None
        with torch.no_grad():
            # LPIPS expects [-1, 1].
            p = pred.clamp(0, 1) * 2.0 - 1.0
            g = gt.clamp(0, 1) * 2.0 - 1.0
            return float(self._lpips(p, g).mean().item())


# ---------------------------------------------------------------------------
# Latency timing
# ---------------------------------------------------------------------------


def time_upscaler(
    upscaler: Upscaler,
    lr: torch.Tensor,
    scale: float,
    device: torch.device,
    runs: int,
    warmup: int,
) -> dict:
    """Returns {mean_ms, p50_ms, p95_ms}. ``lr`` already on ``device``."""
    for _ in range(warmup):
        _ = upscaler(lr, scale).image
    _sync(device)

    samples_ms: List[float] = []
    for _ in range(runs):
        _sync(device)
        t0 = time.perf_counter()
        _ = upscaler(lr, scale).image
        _sync(device)
        samples_ms.append((time.perf_counter() - t0) * 1000.0)

    samples_ms.sort()
    return {
        "mean_ms": statistics.fmean(samples_ms),
        "p50_ms": samples_ms[len(samples_ms) // 2],
        "p95_ms": samples_ms[max(0, int(len(samples_ms) * 0.95) - 1)],
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def run(
    sintel_root: Path,
    scale: float,
    output_csv: Path,
    baselines: Iterable[str],
    max_sequences: int,
    runs: int,
    warmup: int,
    device_pref: str,
) -> List[dict]:
    device = pick_device(device_pref)
    print(f"[run_baselines] device={device}, scale={scale}, runs={runs}, warmup={warmup}",
          file=sys.stderr)

    frames = collect_test_set(sintel_root, scale=scale, max_sequences=max_sequences)
    print(f"[run_baselines] test set: {len(frames)} frame(s) from {len(frames)} sequence(s)",
          file=sys.stderr)

    metrics = _Metrics(device)
    rows: List[dict] = []
    for bname in baselines:
        upscaler = make(bname)
        for fr in frames:
            lr = fr.lr.unsqueeze(0).to(device)
            gt = fr.hr.unsqueeze(0).to(device)
            with torch.no_grad():
                pred = upscaler(lr, scale).image
            row = {
                "baseline": bname,
                "sequence": fr.sequence,
                "frame": fr.name,
                "scale": scale,
                "psnr_db": psnr(pred, gt),
                "ssim": metrics.ssim(pred, gt),
                "lpips_vgg": metrics.lpips(pred, gt),
            }
            t = time_upscaler(upscaler, lr, scale, device, runs=runs, warmup=warmup)
            row.update(t)
            row["device"] = str(device)
            rows.append(row)
            lpips_str = f"{row['lpips_vgg']:.4f}" if row["lpips_vgg"] is not None else "n/a"
            print(
                f"  {bname:8s} {fr.sequence:14s} "
                f"PSNR={row['psnr_db']:5.2f} SSIM={row['ssim']:.4f} "
                f"LPIPS={lpips_str} mean={row['mean_ms']:.2f}ms",
                file=sys.stderr,
            )

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "baseline", "sequence", "frame", "scale",
        "psnr_db", "ssim", "lpips_vgg",
        "mean_ms", "p50_ms", "p95_ms", "device",
    ]
    with output_csv.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"[run_baselines] wrote {len(rows)} rows -> {output_csv}", file=sys.stderr)
    return rows


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--sintel-root", type=Path, default=Path("data/sintel"))
    p.add_argument("--scale", type=float, default=2.0)
    p.add_argument("--output", type=Path, default=Path("bench_results.csv"))
    p.add_argument("--baselines", nargs="+", default=["bicubic", "lanczos"])
    p.add_argument("--max-sequences", type=int, default=10)
    p.add_argument("--runs", type=int, default=100)
    p.add_argument("--warmup", type=int, default=10)
    p.add_argument("--device", choices=("auto", "cpu", "mps"), default="auto")
    args = p.parse_args(argv)

    try:
        run(
            sintel_root=args.sintel_root,
            scale=args.scale,
            output_csv=args.output,
            baselines=args.baselines,
            max_sequences=args.max_sequences,
            runs=args.runs,
            warmup=args.warmup,
            device_pref=args.device,
        )
    except FileNotFoundError as exc:
        print(f"[run_baselines] FATAL: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
